package telas;


public class TelaDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDashboard.class.getName());

    
    public TelaDashboard() {
        initComponents();
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblCadastroPeritos = new javax.swing.JLabel();
        lblCadastroAlvaras = new javax.swing.JLabel();
        lblAuditoria = new javax.swing.JLabel();
        lblBackup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(70, 90, 140));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SISTEMA PERITOS");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Versão 1.0 - Desktop");

        lblDashboard.setBackground(new java.awt.Color(90, 110, 160));
        lblDashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Align-Vertical-Bottom--Streamline-Outlined-Material-Symbols.png"))); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDashboard.setIconTextGap(15);
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
        });

        lblCadastroPeritos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCadastroPeritos.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroPeritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Person--Streamline-Outlined-Material-Symbols.png"))); // NOI18N
        lblCadastroPeritos.setText("Cadastro Peritos");
        lblCadastroPeritos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastroPeritos.setIconTextGap(15);
        lblCadastroPeritos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroPeritosMouseClicked(evt);
            }
        });

        lblCadastroAlvaras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCadastroAlvaras.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroAlvaras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/List--Streamline-Outlined-Material-Symbols.png"))); // NOI18N
        lblCadastroAlvaras.setText("Cadastro de Alvarás");
        lblCadastroAlvaras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadastroAlvaras.setIconTextGap(15);
        lblCadastroAlvaras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastroAlvarasMouseClicked(evt);
            }
        });

        lblAuditoria.setBackground(new java.awt.Color(70, 90, 140));
        lblAuditoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblAuditoria.setForeground(new java.awt.Color(255, 255, 255));
        lblAuditoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/History--Streamline-Outlined-Material-Symbols.png"))); // NOI18N
        lblAuditoria.setText("Auditoria/Histórico");
        lblAuditoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAuditoria.setIconTextGap(15);
        lblAuditoria.setOpaque(true);
        lblAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuditoriaMouseClicked(evt);
            }
        });

        lblBackup.setBackground(new java.awt.Color(70, 90, 140));
        lblBackup.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblBackup.setForeground(new java.awt.Color(255, 255, 255));
        lblBackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Database--Streamline-Outlined-Material-Symbols.png"))); // NOI18N
        lblBackup.setText("Backup e Importação");
        lblBackup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBackup.setIconTextGap(15);
        lblBackup.setOpaque(true);
        lblBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackupMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadastroPeritos)
                    .addComponent(lblCadastroAlvaras)
                    .addComponent(lblAuditoria)
                    .addComponent(lblBackup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(lblDashboard)
                .addGap(27, 27, 27)
                .addComponent(lblCadastroPeritos)
                .addGap(31, 31, 31)
                .addComponent(lblCadastroAlvaras)
                .addGap(32, 32, 32)
                .addComponent(lblAuditoria)
                .addGap(33, 33, 33)
                .addComponent(lblBackup)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblCadastroPeritosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroPeritosMouseClicked
        TelaDadosPeritos tela = new TelaDadosPeritos();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCadastroPeritosMouseClicked

    private void lblCadastroAlvarasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastroAlvarasMouseClicked
        TelaRelatorioAlvaras tela = new TelaRelatorioAlvaras();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCadastroAlvarasMouseClicked

    private void lblAuditoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuditoriaMouseClicked
        new TelaAuditoria().setVisible(true);
    }//GEN-LAST:event_lblAuditoriaMouseClicked

    private void lblBackupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackupMouseClicked
        new TelaBackup().setVisible(true);
    }//GEN-LAST:event_lblBackupMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAuditoria;
    private javax.swing.JLabel lblBackup;
    private javax.swing.JLabel lblCadastroAlvaras;
    private javax.swing.JLabel lblCadastroPeritos;
    private javax.swing.JLabel lblDashboard;
    // End of variables declaration//GEN-END:variables
}
